# -*- coding: utf-8 -*-
"""naver_api_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYxjlk9zSzfXb1pXOQBjMIBWSDEhsML7

* [네이버 오픈 API 목록 - INTRO](https://developers.naver.com/products/intro/plan/plan.md)
* [애플리케이션 - NAVER Developers](https://developers.naver.com/apps/#/list)
* [네이버 데이터랩](https://datalab.naver.com/)
"""

from google.colab import userdata
# 주석 처리 cmd + /

"""### **블로그 기반 정성 데이터 및 버즈량 수집**

- **목적:** "2030 가성비 키워드" 분석 및 연령별 선물 선택 기준(포장, 배송 등) 추출.
- **수집 데이터:** **검색 API(블로그)**의 검색 결과 및 요약 정보.
- **액션:** "가성비 명절 선물", "부모님 명절 선물 브랜드" 등의 키워드로 검색된 블로그 포스트의 총 개수(`total`)와 본문 요약(`description`) 텍스트를 수집합니다.
"""

import os
import sys
import urllib.request
import json
from google.colab import userdata

# Retrieve Client ID and Client Secret from Colab secrets
CLIENT_ID = os.getenv("NAVER_CLIENT_ID")
CLIENT_SECRET = os.getenv("NAVER_CLIENT_SECRET")

# 수집하고자 하는 키워드 리스트
keywords = ["가성비 명절 선물", "부모님 명절 선물 브랜드"]
gen_keywords = ["부모님 명절 선물", "부모님 추석 선물", "부모님 설 선물", "사회초년생 명절 선물", "20대 명절 선물"]

for keyword in keywords:
    # 검색어는 UTF-8로 인코딩되어야 합니다. [4], [5]
    encText = urllib.parse.quote(keyword)

    # 블로그 검색 결과를 JSON 형식으로 반환하는 URL입니다. [6], [7]
    # display 파라미터로 한 번에 가져올 결과 개수를 설정할 수 있습니다 (최대 100개). [4]
    url = "https://openapi.naver.com/v1/search/blog.json?query=" + encText + "&display=10"

    request = urllib.request.Request(url)

    # HTTP 요청 헤더에 클라이언트 아이디와 시크릿을 추가합니다. [4], [1]
    request.add_header("X-Naver-Client-Id", CLIENT_ID)
    request.add_header("X-Naver-Client-Secret", CLIENT_SECRET)

    try:
        response = urllib.request.urlopen(request)
        rescode = response.getcode()

        if rescode == 200:
            response_body = response.read()
            # JSON 데이터를 파싱합니다. [8]
            data = json.loads(response_body.decode('utf-8'))

            print(f"\n[키워드: {keyword}]")
            # 전체 검색 결과 개수(total) 출력 [8], [9]
            print(f"총 검색 결과 개수(total): {data.get('total')}")

            # 개별 블로그 포스트의 요약 정보(description) 추출 [8], [9]
            print("--- 본문 요약 리스트 ---")
            for item in data.get('items', []):
                # 요약 정보 내의 <b> 태그 등을 제거하여 출력하면 분석이 더 용이합니다.
                description = item.get('description').replace('<b>', '').replace('</b>', '')
                print(f"- {description}")

        else:
            print(f"Error Code: {rescode}")

    except Exception as e:
        print(f"에러 발생: {e}")





import requests
import pandas as pd

# 쇼핑 데이터랩 - 카테고리 내 키워드 트렌드 URL
url = "https://openapi.naver.com/v1/datalab/shopping/category/keywords"

# 분석 기간 및 필터 설정
start_date = "2025-01-01"
end_date = "2025-12-31"
time_unit = "date"   # date / week / month 가능

device = "pc"        # "pc", "mo", "all"
gender = "f"         # "m", "f", "all"
ages = ["10", "20", "30", "40"]  # 문자열 배열

# 비교할 쇼핑 카테고리 (화장품/미용)
category_code = "50000002"  # 화장품/미용

# 비교할 키워드 그룹 (선크림 vs 톤업 선크림)
keyword_groups = [
    {"name": "선크림", "param": ["선크림"]},
    {"name": "톤업 선크림", "param": ["톤업 선크림"]}
]

# 요청 body 구성
body = {
    "startDate": start_date,
    "endDate": end_date,
    "timeUnit": time_unit,
    "category": category_code,
    "keyword": keyword_groups,
    "device": device,
    "gender": gender,
    "ages": ages
}

# 요청 헤더
headers = {
    "X-Naver-Client-Id": CLIENT_ID,
    "X-Naver-Client-Secret": CLIENT_SECRET,
    "Content-Type": "application/json"
}

# 결과를 저장할 리스트
all_results = []

# API 요청
response = requests.post(url, headers=headers, json=body)

# 응답 처리
if response.status_code == 200:
    data = response.json()

    # results 구조 파싱
    for result in data["results"]:
        keyword_name = result["title"]  # "선크림", "톤업 선크림"

        for dp in result["data"]:
            all_results.append({
                "date": dp["period"],
                "keyword": keyword_name,
                "ratio": dp["ratio"]
            })
else:
    print(f"API 요청 실패: 상태 코드 {response.status_code}")
    print("오류 메시지:", response.text)

# 데이터프레임 생성
df = pd.DataFrame(all_results)

# 결과 출력 및 저장
if not df.empty:
    print("수집된 데이터:")
    print(df.head())

    # CSV로 저장
    df.to_csv("naver_sunscreen_vs_toneup.csv", index=False)
    print("분석 결과가 'naver_sunscreen_vs_toneup.csv'에 저장되었습니다.")
else:
    print("수집된 데이터가 없습니다.")

df

df.info()

df.describe()

df.describe(include='object')

df['keyword'].value_counts()

print(df.groupby('keyword')['ratio'].describe())

!pip install -q koreanize-matplotlib

import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

plt.figure(figsize=(14, 7))
sns.lineplot(data=df, x='date', y='ratio', hue='keyword', marker='o', errorbar=None)
plt.title('선크림 vs 톤업 선크림 트렌드 비교 (Ratio)')
plt.xlabel('날짜')
plt.ylabel('Ratio')
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='키워드')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

# Ensure 'date' column is datetime and 'month' is extracted
if not pd.api.types.is_datetime64_any_dtype(df['date']):
    df['date'] = pd.to_datetime(df['date'])
if 'month' not in df.columns:
    df['month'] = df['date'].dt.month

# 월별, 키워드별 평균 ratio 계산
monthly_keyword_ratio = df.groupby(['month', 'keyword'])['ratio'].mean().reset_index()

plt.figure(figsize=(12, 6))
sns.lineplot(data=monthly_keyword_ratio, x='month', y='ratio', hue='keyword', marker='o')
plt.title('월별 선크림 vs 톤업 선크림 평균 Ratio 비교')
plt.xlabel('월')
plt.ylabel('평균 Ratio')
plt.xticks(range(1, 13)) # 1월부터 12월까지 표시
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(title='키워드')
plt.tight_layout()
plt.show()

df['keyword'].value_counts()

# prompt: koreanize_matplotlib 설치 및 설정

!pip install -q koreanize-matplotlib

import matplotlib.pyplot as plt
import koreanize_matplotlib

# prompt: df 변수의 날짜를 월, 요일로 변환하고 월별 요일별 분석코드 작성

# 날짜 열을 datetime 객체로 변환
df['date'] = pd.to_datetime(df['date'])

# 월과 요일 추출
df['month'] = df['date'].dt.month
df['dayofweek'] = df['date'].dt.dayofweek  # 0: 월요일, 6: 일요일

# 월별, 요일별 분석
monthly_analysis = df.groupby('month')['ratio'].mean()
print("월별 평균 ratio:")
print(monthly_analysis)

daily_analysis = df.groupby('dayofweek')['ratio'].mean()
print("\n요일별 평균 ratio:")
print(daily_analysis)

# 월별, 요일별 시각화 (선택 사항)
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
monthly_analysis.plot(kind='bar')
plt.title('Monthly Average Ratio')
plt.xlabel('Month')
plt.ylabel('Average Ratio')

plt.subplot(1, 2, 2)
daily_analysis.plot(kind='bar')
plt.title('Daily Average Ratio')
plt.xlabel('Day of Week (0:Monday, 6:Sunday)')
plt.ylabel('Average Ratio')

plt.tight_layout()
plt.show()

from google.colab import userdata
CLIENT_ID = userdata.get('client_id')
CLIENT_SECRET = userdata.get('client_secret')

import requests
import pandas as pd
import re
import html

# 네이버 쇼핑 검색 API URL
# 문서 기준: https://openapi.naver.com/v1/search/shop
# JSON 응답을 강제하려면 보통 .json을 붙여 사용합니다.
url = "https://openapi.naver.com/v1/search/shop.json"

# 선크림 관련 주요 키워드 (원하시는 대로 추가/삭제 가능)
keywords = [
    "선크림",
    "톤업 선크림",
    "수분 선크림",
    "지성 선크림",
    "민감성 선크림"
]

# HTML 태그 제거 + 엔티티 디코딩 함수
def clean_title(raw_title: str) -> str:
    # <b>...</b> 같은 태그 제거
    no_tag = re.sub(r"<.*?>", "", raw_title)
    # &amp; 같은 HTML 엔티티 디코딩
    return html.unescape(no_tag).strip()

# 공통 헤더
headers = {
    "X-Naver-Client-Id": CLIENT_ID,
    "X-Naver-Client-Secret": CLIENT_SECRET,
}

all_items = []

for q in keywords:
    # 한 키워드당 상위 100개까지 수집 (display 최대 100)
    params = {
        "query": q,
        "display": 100,  # 수집할 개수 (1~100)
        "start": 1,      # 시작 위치
        "sort": "sim"    # sim(유사도순), date(날짜순), asc/desc(가격)
    }

    response = requests.get(url, headers=headers, params=params)

    if response.status_code == 200:
        data = response.json()

        for item in data.get("items", []):
            product_name_raw = item.get("title", "")
            product_name = clean_title(product_name_raw)

            all_items.append({
                "keyword": q,
                "product_name": product_name,
                "link": item.get("link"),
                "mall_name": item.get("mallName"),
                "product_id": item.get("productId"),
                "lprice": item.get("lprice"),  # 최저가
                "hprice": item.get("hprice")   # 최고가
            })
    else:
        print(f"[ERROR] 키워드 '{q}' 호출 실패 - 상태 코드: {response.status_code}")
        print("오류 메시지:", response.text)

# DataFrame 생성
df = pd.DataFrame(all_items)

if not df.empty:
    # 중복 제품명 제거 (원하면 주석 해제)
    # df = df.drop_duplicates(subset=["product_name"])

    print("수집된 선크림 제품 예시:")
    print(df.head())

    # CSV 저장
    df.to_csv("naver_sunscreen_products.csv", index=False, encoding="utf-8-sig")
    print("제품명 리스트가 'naver_sunscreen_products.csv'로 저장되었습니다.")
else:
    print("수집된 데이터가 없습니다.")

# Ensure 'lprice' is numeric (already done, but good practice)
df['lprice'] = pd.to_numeric(df['lprice'], errors='coerce')

# Drop rows where 'lprice' is NaN to avoid errors in plotting
df_filtered = df.dropna(subset=['lprice'])

plt.figure(figsize=(10, 6))
sns.histplot(df_filtered['lprice'], bins=50, kde=True)
plt.title('제품 최저 가격(lprice) 분포')
plt.xlabel('가격 (원)')
plt.ylabel('제품 수')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()



"""# Task
Modify the existing blog search code to extract and store the total search results and descriptions for the keywords "가성비 명절 선물" and "부모님 명절 선물 브랜드". Then, generate a word cloud from the collected blog descriptions after preprocessing, and create a bar chart to compare the total search results for each keyword. Finally, analyze the generated word cloud and bar chart to provide insights.

## Extract and Store Blog Data

### Subtask:
Modify the existing blog search code (cell `BkWcyR6k-gtE`) to store the `total` search results for each keyword and all `description` texts into a list of dictionaries. This will make the data available for subsequent visualizations.

**Reasoning**:
The subtask requires modifying the existing blog search code to store the total search results and description texts for each keyword into a list of dictionaries. This code block will implement the required changes by initializing an empty list, extracting the necessary data within the loop, and appending it to the list.
"""

import os
import sys
import urllib.request
import json
from google.colab import userdata

# Retrieve Client ID and Client Secret from Colab secrets
CLIENT_ID = userdata.get('client_id')
CLIENT_SECRET = userdata.get('client_secret')

# 수집하고자 하는 키워드 리스트
keywords = ["가성비 명절 선물", "부모님 명절 선물 브랜드"]
gen_keywords = ["부모님 명절 선물", "부모님 추석 선물", "부모님 설 선물", "사회초년생 명절 선물", "20대 명절 선물"]

# 블로그 데이터를 저장할 리스트 초기화
blog_data = []

for keyword in keywords:
    # 검색어는 UTF-8로 인코딩되어야 합니다. [4], [5]
    encText = urllib.parse.quote(keyword)

    # 블로그 검색 결과를 JSON 형식으로 반환하는 URL입니다. [6], [7]
    # display 파라미터로 한 번에 가져올 결과 개수를 설정할 수 있습니다 (최대 100개). [4]
    url = "https://openapi.naver.com/v1/search/blog.json?query=" + encText + "&display=100" # display 100으로 늘려 더 많은 description 수집

    request = urllib.request.Request(url)

    # HTTP 요청 헤더에 클라이언트 아이디와 시크릿을 추가합니다. [4], [1]
    request.add_header("X-Naver-Client-Id", CLIENT_ID)
    request.add_header("X-Naver-Client-Secret", CLIENT_SECRET)

    try:
        response = urllib.request.urlopen(request)
        rescode = response.getcode()

        if rescode == 200:
            response_body = response.read()
            # JSON 데이터를 파싱합니다. [8]
            data = json.loads(response_body.decode('utf-8'))

            # 전체 검색 결과 개수(total) 추출
            total_results = data.get('total', 0)

            # 개별 블로그 포스트의 요약 정보(description) 리스트 추출 및 정리
            descriptions = []
            for item in data.get('items', []):
                description = item.get('description', '').replace('<b>', '').replace('</b>', '')
                descriptions.append(description)

            # 추출된 데이터를 딕셔너리 형태로 저장
            blog_entry = {
                'keyword': keyword,
                'total_results': total_results,
                'descriptions': descriptions
            }
            blog_data.append(blog_entry)

            print(f"\n[키워드: {keyword}]")
            print(f"총 검색 결과 개수(total): {total_results}")
            print("--- 본문 요약 리스트 ---")
            for desc in descriptions:
                print(f"- {desc}")

        else:
            print(f"Error Code: {rescode}")

    except Exception as e:
        print(f"에러 발생: {e}")

# 수집된 blog_data 출력
print("\n--- 수집된 blog_data ---")
for entry in blog_data:
    print(f"Keyword: {entry['keyword']}, Total Results: {entry['total_results']}, Descriptions Count: {len(entry['descriptions'])}")
    # Optionally, print first few descriptions to verify
    # for i, desc in enumerate(entry['descriptions'][:3]):
    #     print(f"  Desc {i+1}: {desc}")

"""**Reasoning**:
The next step is to preprocess the collected blog descriptions by concatenating them into a single string for each keyword. This aggregated text will then be used to generate word clouds, fulfilling the first part of the main task's visualization requirement.


"""

from collections import Counter
import re

# Initialize a dictionary to store combined descriptions for each keyword
combined_descriptions = {}

for entry in blog_data:
    keyword = entry['keyword']
    # Join all descriptions for the current keyword into a single string
    text = " ".join(entry['descriptions'])
    combined_descriptions[keyword] = text

print("--- Combined Descriptions for each keyword ---")
for keyword, text in combined_descriptions.items():
    print(f"Keyword: {keyword}\nSample Text (first 200 chars): {text[:200]}...\n")

"""**Reasoning**:
To generate meaningful word clouds from the Korean text, it's essential to tokenize the text and remove common Korean stopwords. The `konlpy` library provides effective tools for this, specifically `Mecab` for tokenization, and `wordcloud` will be used for visualization.


"""

import matplotlib.pyplot as plt
from wordcloud import WordCloud
from konlpy.tag import Mecab
import koreanize_matplotlib # To ensure Korean characters are displayed correctly in plots

# Install required libraries if not already installed
!pip install -q konlpy wordcloud
!apt-get update -qq
!apt-get install -y fonts-nanum-extra
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git
!bash Mecab-ko-for-Google-Colab/install_mecab-0.996-ko-0.9.2.sh

# Re-configure matplotlib to use the installed Nanum font
import matplotlib.font_manager as fm
fm._rebuild()

# Initialize Mecab tokenizer
mecab = Mecab()

# Define Korean stopwords (can be expanded)
korean_stopwords = [
    '이', '그', '저', '것', '수', '등', '들', '다', '의', '가', '을', '를', '에', '와', '과', '도', '으로', '고', '면', '는', '으로', '로', '에', '게', '에서', '에게',
    '하다', '있다', '되다', '이다', '입니다', '습니다', '어요', '아요', '어요', '아요', '합니다', '하고', '한다', '하는', '될', '됨', '입니다', '이예요', '있습니다',
    '위해', '통해', '이번', '대한', '정말', '진짜', '너무', '정성', '그리고', '해서', '있어', '아니라', '같이', '같은', '처럼', '많은', '좋은', '가장', '선물',
    '명절', '부모님', '추천', '세트', '제품', '생각', '말', '이야기', '요즘', '아래', '링크', '확인', '가능', '드려요', '후기', '하나', '하나', '두', '분', '월', '일', '년', '때',
    '마음', '준비', '제', '내', '모든', '그것', '저희', '가지', '수', '다른', '어떤', '이런', '저런', '어느', '더', '좀', '잘', '새로운', '벌써', '다가오는', '이번',
    '어요', '세요', '아요', '해요', '합니다', '합니다', '입니다', '이세요', '있어요', '돼요', '되어', '있습니다', '드립니다', '드렸습니다', '할', '수', '있도록', '합니다',
    '해서는', '또한', '하지만', '그리고', '그렇지만', '물론', '혹은', '아니면', '따라', '따라서', '부터', '까지', '으로', '로서', '하면', '하더라도', '할수록', '하기에',
    '합니다', '습니다', '입니다', '해요', '있습니다', '있어요', '되었다', '입니다', '됩니다', '할수', '할', '있음', '만큼', '해서', '하고', '또한', '으로도', '같은',
    '전할', '소개해', '드리는', '보세요', '드린', '자세한', '정보는', '아래', '링크에서', '확인', '가능합니다', '베스트', '정리', '민족', '고민은', '역시', '어떤', '것',
    '전하기는', '누구나', '좋아하는', '선택지인', '것', '같아요', '투뿔', '한우의', '퀄리티와', '추석', '마음에', '들었어요', '가성비', '선물', '찾고', '직접', '만나지', '못해',
    '카톡', '선물하기로', '선물을', '준비해야', '하는', '추천합니다', '배송받아', '보았는데요', '배송은', '냉동된', '상태로', '아이스박스에', '넣어', '괜히', '아니랍니다',
    '진짜', '쫄깃쫄깃하고', '시간이', '지나도', '굳지않는', '떡이라서', '정리해보면', '과하게', '달지', '않은', '팥', '맛을', '좋아하는', '찾는', '다음', '다시', '찾게', '될',
    '장복용', '과자공방', '화과자였답니다', '없는', '셋트로', '소중한', '분께', '마음을', '전해', '보세요', '갤러리', '컬렉션', '제품은', '여러가지', '사항을', '고려해서',
    '찾고', '찾고', '찾다가', '발견해낸', '좋은', '세트를', '소개해볼게요', '흔한', '확실히', '차별화된', '매력이', '있고', '가격', '부담은', '줄이고', '정성은', '듬뿍', '담긴',
    '선물이라', '매년', '선택하게', '되는', '우메종', '한우선물세트', '고마운', '전하기는', '물론', '누구나', '좋아하는', '선택지인', '같아요', '투뿔', '퀄리티와', '설날',
    '오월수산의', '반건조생선', '세트는', '고급세트까지', '반건조가자미', '반건조생선구이', '반건조조기', '준비가', '한창이에요', '코스트코', '정말', '많아서', '코스트코명절선물',
    '코스트코설날', '코스트코세일', '영양제', '회사', '단체', '바로', '진생가라는', '브랜드의', '홍삼세트인데요', '가격', '성분', '포장', '이렇게', '가지', '부분이', '마음에',
    '들어서', '선택하게', '되었고', '결과적으로', '직원과', '임원분들', '반응', '모두', '좋았어요', '가성비', '최고', '한국인', '밥상에', '빠질', '수', '없는', '참기름', '명절을',
    '앞두고', '찾는', '분들께도', '국내산', '정방앗간', '후기', '위에', '스토어에서', '구매', '가능하다', '이렇게', '해드세요', '허니바이허니', '꿀스틱', '정말', '지금',
    '할인', '중이니', '이벤트', '기간', '놓치지', '마시고', '건강을', '또', '합리적인', '가격대로', '직장', '동료나', '친한', '지인', '어린이집', '선생님이나', '학원', '선생님에게',
    '정관장선물세트인가', '제가', '드릴', '때', '부모님도', '아이도', '좋아하는', '견과류', '청정마루', '안녕하세요', '추석이', '다들', '바쁘시죠', '고르려고', '며칠', '동안',
    '머리를', '싸매다', '드디어', '좋은', '아이템을', '너무', '가볍게', '보이면', '아쉽고', '과하게', '비싸면', '부담스럽고', '쉽지', '않아요', '특히', '감사한', '지인에게',
    '드릴', '선물은', '선택지가', '지나가도', '계속', '쓰는', '트레이더스', '모음', '안녕하세요', '리빙', '인플루언서', '둘러보셔도', '좋을', '것', '같아요', '스팸선물세트',
    '실속형', '건강식품', '홍삼', '위해', '준비', '완료', '센스가', '있으면서도', '괜찮은', '제품이', '없을까를', '살펴보던', '와중에', '알게', '된', '활기력은', '패키지',
    '괜찮은', '홍삼', '제품이더라고요', '호불호', '없이', '질리지', '않는', '은은하고', '부드러운', '향의', '바디워시', '더마힐세트', '리뉴얼된', '약산성', '펩타이드', '시카',
    '바디워시를', '작년', '사용했으니', '한', '달', '조금', '넘게', '사용', '처음부터', '끝까지', '수제방식으로', '만든', '디저트라', '그런지', '확실히', '맛있더라구요',
    '다가오는', '설명절에', '어떤선물할지', '고민중이시라면', '붓세선물세트', '살포시', '좋아', '기름기', '많은', '음식을', '먹은', '뒤', '온', '가족들이', '나눠먹기', '부담없는',
    '음료랍니다', '요', '음료도', '적어', '선물용으로', '사랑받고있답니다', '인삼선물세트', '인삼을', '선별해', '담고', '고급스러운', '보자기', '정육터', '정육점', '한우선물세트',
    '준비했어요', '글', '사진', '꽃냥이', '육아맘', '같아', '소개해', '드릴까해요', '오늘', '소개해', '드릴', '바로', '한우선물세트인데요', '극강의', '부담없는', '절대감',
    '숙성한우', '준비할까', '고민이', '많아지죠', '받는', '사람도', '만족하고', '주는', '사람도', '부담되지', '않는', '찾기가', '결혼답례품', '아이들', '간식으로도', '다양하게',
    '활용하기', '좋을', '듯하다', '장인이', '만든', '붓세인데', '가격도', '합리적이다', '개', '원', '만하면', '고려할', '케이스도', '바로', '작년까지만', '백화점', '포장',
    '코너', '앞에서', '멍하니', '있었는데', '올해는', '다르답니다', '제가', '만원대로', '해결한', '그것도', '센스있는', '고르는', '법', '전하기', '머릿속이', '복잡해집니다', '친정',
    '시댁', '회사', '상사님', '평소', '신세', '지던', '분들까지', '리스트를', '쫙', '적어보면', '한두', '곳이', '종류', '가격', '코스트코', '알려드려볼게요', '양재점', '빠진',
    '찾게', '된다', '내가', '선택한', '정육터', '한우', '세트', '다가오는', '설', '기분', '울산', '고기', '인증', '거창', '고급', '도라지정과', '아주', '작은', '기업을',
    '운영', '중인데요', '설날', '시즌', '솔직히', '매년', '오는', '돌아올', '때마다', '똑같이', '고민돼요', '거래처', '설날', '오월수산', '세트', '부모님', '건강', '식단',
    '트레이너', '식단', '단백질', '보충', '생선', '요리', '합리적인', '금액대지만', '겉보기에', '훨씬', '비싸보이는', '이야말로', '감사의', '즐길', '수', '있는', '건강한',
    '하나로도', '다가올', '선물은', '가격만', '비싸다고', '좋은', '아니잖아요', '받는', '사람이', '얼마나', '해당', '포스팅은', '제품을', '제공받아', '직접', '체험', '솔직하게',
    '작성하였습니다', '한돈', '다가오는', '고민', '라면', '장우가든', '국내산', '돼지고기', '상품', '좋은', '있었어요', '쇼핑몰로', '설날', '알뜰하게', '준비하는', '방법',
    '젤', '고민되는', '준비죠', '경기', '어렵지만', '친척', '지인', '거래처까지', '챙기다', '보면', '생각보다', '들어가는', '있었음', '스팸', '복합', '호', '사용법과', '분석',
    '되면', '준비할지', '고민이', '아래', '자세히', '보기', '미래웰푸드', '오란다', '유자', '다가오면', '항상', '되는', '사람', '이나', '지인에게', '무난하지만', '인상적인',
    '전하고', '있습니다', '쇼핑백', '포함으로', '나온', '호', '호', '호', '호의', '비교를', '가져왔어요', '가장', '많이', '하는', '호', '사용한', '때', '좋은', '효도선물이죠',
    '경주', '생약', '청해솔', '침향환', '경주', '생약', '청해솔', '침향환', '침향에', '존재하는', '유효성분을', '그대로', '유지시키기', '위해서', '저온건조', '공법으로', '진품',
    '침향은', '찾는다면', '선택이', '될것', '같아요', '바싹', '잡곡', '세트는', '포장부터', '깔끔하고', '고급스러워요', '별도의', '쇼핑백이', '함께', '구성되어', '있어서',
    '그대로', '들고', '인사드리', '좋고', '분위기에도', '소잇', '쇼핑몰로', '준비하는', '방법', '제일', '고민되는', '준비죠', '요즘', '경기가', '어렵지만', '친척', '지인',
    '거래처까지', '챙기다', '보면', '생각보다', '들어가는', '있었음', '설', '만원대', '괜찮을거', '싶어', '소개하려구요', '국산', '착즙배즙', '배즙', '행복', '박스', 'ml',
    '팩', '넉넉한', '구성으로', '남녀노소', '누구나', '부담없이', '매일', '마실', '수', '있는', '건강', '음료로도', '산', '물', '지인', '친구', '구입하기', '좋은',
    '괜찮으니', '간편하게', '일이', '있거나', '때', '드리실때', '추천드려요', '대천', '곱창김', '대천', '곱창캔김', '부모님', '대천', '곱창김', '곱창캔김', '추천', '한돈',
    '만원대', '만원대', '쇼핑', '이마트에서', '구매할', '수', '있는', '와인', '몽그라스', '그랑리제르바', '만나보', '게다가', '세트', '단위', '구매시', '할인의', '파격',
    '할인이', '적용되어', '좋게', '구매할', '수', '있어서', '더욱', '본', '포스트는', '한국인삼공사로부터', '소정의', '활동료와', '제품을', '지급받고', '작성되었습니다',
    '첫', '인사', '추석', '설', '인사드려요', '벌써', '달력을', '보니', '설명절', '한우', '함께', '모여', '지나고', '난뒤', '기억에', '남는', '에피소드', '중에', '하나는',
    '맛있게', '먹은', '이야기', '받은', '소고기', '맛이', '기가', '막혔다', '이야기', '듣고', '싶으시죠', '이런', '덕분에', '좋은', '말이', '자연스럽게', '떠올랐어요',
    '유자오란다라는', '처음', '먹어보는', '분들도', '많을', '텐데', '국내산', '남해', '유자로', '만든', '유자청을', '사용했다는', '점이', '특히', '인상적이었어요', '그러다',
    '보면', '선물을', '깜빡', '하는', '경우도', '생기니', '이번에는', '조금', '더', '서둘러서', '챙겨보면', '좋을거', '같아서', '세트를', '준비해', '왔어요', '개인적으로', '먹거리',
    '가장', '기분이', '좋은', '생각이', '만원대라면', '면에서도', '충분히', '매력적이죠', '실속형', '확인된', '만족감', '약과', '마련', '약과', '설날', '만원대', '호박약과',
    '아이키우는', '집에서는', '절대', '없어서는', '가격도', '합리적이라서', '여러개로', '구비해', '주시거나', '다가오는', '해도', '코코도르', '선물세트', '어떠신가용',
    '빠잇', '코코도르', '편하고', '좋게', '즐길', '수', '있어서', '좋았다', '품질', '정육터', '한우', '세트', '다가오는', '설', '기분', '울산', '좋은', '한우', '상품',
    '거창', '명절', '추천', '고급', '도라지정과', '저는', '아주', '작은', '기업을', '운영', '중인데요', '설날', '시즌', '솔직히', '매년', '오는', '돌아올', '때마다',
    '똑같이', '고민돼요', '거래처', '코스트코', '추천상품', '리스트', '코스트코', '추석', '이하', '대부터', '시작해서', '만원대까지', '코스트코', '종류', '알려드려볼게요',
    'COSTCO', '양재점', '빠진', '대가', '합리적이라서', '만족했어요', '답례품', '인사', '스승님', '활용하기', '좋겠다고', '구', '품격', '용도에', '따라서', '구이용을',
    '좋아하신다면', '갈비나', '한우', '구이', '세트를', '요리를', '풍성하게', '준비하신다면', '찜갈비를', '주문해', '보세요', '현재', '제품별로', '할인이', '들어가',
    '맛있는김', '해녹', '햇김', '곱창김', '돌김', '아이반찬', '없어서는', '가격도', '합리적이라서', '구비해주시거나', '다가오는', '해도', '너무', '좋을', '것', '같아요',
    '이마트에서', '구매할', '수', '있는', '와인', '몽그라스', '그랑리제르바', '만나보', '게다가', '세트', '단위', '구매시', '할인', '적용되어', '좋게', '구매할',
    '있어서', '더욱', '본', '포스트는', '한국인삼공사로부터', '소정의', '활동료와', '제품을', '지급받고', '작성되었습니다', '부모님', '첫', '인사', '추석', '설', '인사드려요',
    '안녕하세요', '진입니다', '벌써', '달력을', '보니', '설명절', '한우', '함께', '모여', '지나고', '난뒤', '기억에', '남는', '에피소드', '중에', '하나는', '맛있게', '먹은',
    '이야기', '받은', '소고기', '맛이', '기가', '막혔다', '이야기', '듣고', '싶으시죠', '이런', '덕분에', '센스있는', '선물', '추천', '만하면', '매력적이죠', '실속형',
    '후기에서', '확인된', '만족감', '만원대', '만원대', '합리적인', '아이템을', '하나', '소개해보려고', '합니다', '집들이', '향수', '선택', '폭이', '센스있는',
    '선물', '추천템이에요', '더욱', '깊고', '진한', '풍미를', '느낄', '수', '있는', '에브리타임', '샷과', '간편하게', '기력을', '북돋을', '수', '있는', '활기력', '가지를',
    '세트로', '담아냈습니다', '장우가든', '돼지고기', '상품', '추천합니다', '상품', '퀄리티', '만족스러운', '고기', '인증', '곧', '다가오는', '선물', '고민', '중이라면',
    '스팸', '복합', '호', '사용법과', '분석', '되면', '준비할지', '고민이', '아래', '자세히', '보기', '미래웰푸드', '오란다', '유자', '다가오면', '항상', '되는',
    '사람', '이나', '지인에게', '무난하지만', '인상적인', '전하고', '있습니다', '쇼핑백', '포함으로', '나온', '호', '호', '호', '호의', '비교를', '가져왔어요',
    '가장', '많이', '하는', '호', '사용한', '때', '좋은', '효도선물이죠', '경주', '생약', '청해솔', '침향환', '경주', '생약', '청해솔', '침향환', '침향에', '존재하는',
    '유효성분을', '그대로', '유지시키기', '위해서', '저온건조', '공법으로', '진품', '침향은', '찾는다면', '선택이', '될것', '같아요', '바싹', '잡곡', '세트는', '포장부터',
    '깔끔하고', '고급스러워요', '별도의', '쇼핑백이', '함께', '구성되어', '있어서', '그대로', '들고', '인사드리', '좋고', '분위기에도', '소잇', '집들이', '듀벨', '찾으신다면',
    '안녕하세요', '똑순입니다', '지인들의', '집들이나', '다가오면', '비슷한', '고민에', '빠지게', '되죠', '어떤', '골라야', '할지', '고민하다', '보면', '결국', '늘', '부담없는',
    '답례품', '미래웰푸드', '다가오는', '부담스럽지않게', '해', '하나', '소개해드릴게요', '단체', '답례품', '등으로', '추천드리는', '이내의', '합리적인', '골라봤어요',
    '분들께', '특히', '추천드려요', '마다', '고르느라', '아무리', '고민해봐도', '마음이', '안들어서', '고민했던', '적이', '많은데', '결국', '가성비있는', '충분히', '과하지않아도',
    '이하', '만원', '든다는', '센스', '준비해드릴게요', '오늘', '맛집', '소개는', '이것으로', '끝', '아윔비백', '여수', '건어물', '여수', '여수기념품', '단체',
    '추천', '맛집', '오란다', '세트', '미래웰푸드', '좋은', '오란다', '유자오란다', '다가오면', '항상', '되는', '부모님이나', '지인에게', '무난하지만', '인상적인', '전하고',
    '있습니다', '이내의', '합리적인', '충분히', '센스와', '전달할', '수', '있는', '바랍니다', '작은', '하나로도', '풍성하고', '따뜻한', '시간을', '보내시길', '추석', '아니라',
    '받는', '사람이', '얼마나', '좋아하느냐가', '더', '중요하죠', '무엇보다', '하나씩', '개별', '포장되어', '있어서', '위생적이고', '보관도', '쉬워서', '가격인데', '이정도면',
    '혜자', '아닌가요', '다른', '사이트들도', '찾아봤는데', '훨씬', '저렴하고', '무료배송이고', '저처럼', '만원대', '만원대', '찾는다면', '입니다', '만원대', '가격인데',
    '패키지까지', '완벽한', '프리미엄', '더', '좋은', '없을', '듯', '지인', '친구', '등에', '구입하기', '좋은', '선물', '괜찮으니', '간편하게', '일이', '있거나', '때',
    '드리실때', '추천드려요', '대천', '곱창김', '대천', '곱창캔김', '부모님', '대천', '곱창김', '곱창캔김', '추천', '선물', '상품', '추천합니다', '상품', '퀄리티', '만족스러운',
    '고기', '인증', '곧', '다가오는', '선물', '고민', '중이라면', '스팸', '복합', '호', '사용법과', '분석', '되면', '준비할지', '고민이', '아래', '자세히', '보기',
    '미래웰푸드', '오란다', '유자', '다가오면', '항상', '되는', '부모님이나', '지인에게', '무난하지만', '인상적인', '전하고', '있습니다', '쇼핑백', '포함으로', '나온', '호',
    '호', '호', '호의', '비교를', '가져왔어요', '가장', '많이', '하는', '호', '사용한', '때', '좋은', '효도선물이죠', '경주', '생약', '청해솔', '침향환', '경주', '생약',
    '청해솔', '침향환', '침향에', '존재하는', '유효성분을', '그대로', '유지시키기', '위해서', '저온건조', '공법으로', '진품', '침향은', '찾는다면', '선택이', '될것', '같아요',
    '바싹', '잡곡', '세트는', '포장부터', '깔끔하고', '고급스러워요', '별도의', '쇼핑백이', '함께', '구성되어', '있어서', '그대로', '들고', '인사드리', '좋고', '분위기에도',
    '소잇', '정관장은', '120여', '전통의', '대한민국', '대표', '홍삼', '브랜드로', '오랜', '역사와', '기술력을', '가진', '브랜드로', '알려져', '있잖아요', '이런', '배경이',
    '있다는', '점이', '고르는', '입장에서는', '신뢰로', '이어졌어요', '오랜', '기간', '저도', '친구를', '통해', '처음', '접하는', '브랜드이기는', '했지만', '챙겨보니', '원산지에서부터',
    '추출', '공법', '믿을', '수', '있는', 'HACCP', '제조시설까지', '믿을', '수', '있겠다는', '생각이', '들어', '준비하게', '건강식품', '브랜드에요', '모든', '원료는', '클린',
    '네트워크', '시스템을', '통해', '엄격한', '원료', '입고와', '품질', '검사를', '거쳐', '최고의', '한약재', '의약품', '원료와', '식품원료를', '공급하고', '있어요', '선택한',
    '자생', '흑삼', '설명절', '실용성과', '사용', '빈도를', '함께', '고려하다가', '무선', '어깨', '목안마기를', '떠올리게', '이유', '센시안', '목어깨마사지기를', '고르게',
    '된', '이유', '중', '하나는', '브랜드였어', '설', '세일', '한술', '프리미엄', '방짜', '유기', '수저세트', '설날', '해야', '고민', '선물', '하나', '고르려고', '하면',
    '결국', '한두', '두고', '계속', '비교하게', '되잖아요', '여러', '브랜드를', '놓고', '가격대나', '저당쿡', '저당밥솥', '엄마', '아빠를', '위한', '어떻게', '조립되는',
    '브랜드라서', '품질', '면에서도', '신뢰감이', '든다는', '점', '매일', '먹는', '밥인만큼', '아무거나', '쓸수', '없는데', '여러', '합리적', '가격', '요런', '홍삼제품',
    '건강관리', '위해', '꾸준히', '챙기려면', '사실', '가격적인', '면에서도', '부담이', '없어야', '한다고', '생각해요', '브랜드', '인지도가', '하니', '드릴', '더욱', '안심이',
    '본품', '박스', '안에는', '품질보증서도', '들어있었는데', '그래서', '그런지', '지강인', '홍삼정은', '단순히', '판매하는', '아니라', '신뢰를', '챙기려는', '올해는',
    '찾다', '제격인', '떡을', '장만하기로', '했습니다', '겸사겸사', '친척분들께', '간식도', '돌릴', '겸', '댁으로', '주문을', '넣기로', '했습니다', '구매한', '신년', '호는',
    '된', '브랜드의', '늘', '건강관리는', '걱정이었던지라', '챙길', '수', '있는', '선택한', '이유', '프리미엄', '120여년', '이상의', '시댁', '실속있는', '고함량', '홍삼진액스틱',
    '예전에는', '명품', '떠올랐는데', '저는', '다음번에', '소식으로', '다시', '돌아오도록', '하겠습니다', '건강식품', '파낙스엠', '휴온스엠', '나돈나산', '파낙스엠', '휴온스엠',
    '정관장은', '엄격한', '품질', '관리로', '믿고', '신뢰할', '수', '있는', '120여', '전통과', '기술력을', '바탕으로', '만든', '처음', '준비하다', '보니', '녹용이', '들어가',
    '제품을', '모델로', '발탁되기도', '오래', '보고', '들어온', '챙겨드리기는', '괜찮은', '정관장', '기다림', '침향환은', '기대만큼', '고급스러운', '패키지와', '함께',
    '품격있는', '선물로', '자신있게', '드리는', '좋은', '선택이', '될수', '있는', '침향환', '홍삼스틱', '준비하는', '만큼', '성분', '과정까지', '신뢰할', '수', '있는', '홍삼',
    '불필요하게', '첨가되는', '부형제는', '최소화하여', '진한', '맛과', '향을', '양가', '인사', '자리에', '들고', '만한', '어른', '조언', '구하기를', '적당한', '찾다가',
    '더한방울', '도라지정과', '선택했어요', '새해', '안부', '인사', '겸해서', '올해', '첫', '마침', '나이', '좋아하시고', '강릉', '브랜드라', '신뢰도도', '있었구요',
    '포장이', '깔끔해서', '슈퍼', '바이탈', '라인은', '이미', '워낙', '좋아서', '고민', '없이', '선택하기', '라인은', '이미', '후기도', '워낙', '고민', '선택하기', '좋은',
    '그리고', '이것은', '한우', '육포', '맥주', '안주', '딱입니다', '추천템', '그리고', '이것은', '한우', '육포', '맥주', '안주', '딱입니다', '추천템', '다양한', '만큼',
    '많은', '나이가', '들면', '들수록', '가장', '중요한', '건강이라고', '생각해요', '그래서', '저는', '건강에', '도움이', '되는', '영양제를', '소개하려고', '합니다',
    '오스트리아는', '이번', '해결입니다', '보스웰리아', '효능', '관절', '관절스타', '관절', '헬스', '규격', '남성', '건강식품', '제약회사', '기반', '설계한', '마시는', '영양제다',
    '영양제는', '원료', '구성과', '패키지라', '다가오는', '추석', '강조하고', '싶다', '헬스', '1위이자', '천만명이', '넘게', '인증한', '수', '있는', '선택', '하겠습니다',
    '좋은상황', '아닌데', '지인들', '사이에서도', '설', '보내드리기', '전에', '제가', '먼저', '맛과', '향을', '경험해', '보고', '싶어서', '미리', '한', '상자를', '준비해',
    '120여', '전통', '역사', '기술력과', '엄격한', '품질관리로', '믿음과', '신뢰성', '있는', '홍삼이', '원료로', '함유된', '제품으로', '합리적인', '가격대로', '가볍게', '전할',
    '센스있는', '설명절', '추천', '아버님', '라이프스타일', '휴바트', '허바트', '휴바트', '발', '다리', '피로가', '심한', '직장인', '여러분', '본인', '피로', '회복용으로도',
    '강추하고', '고민', '중이라면', '족욕기가', '센스있는', '이번에', '배우', '박보검씨가', '모델로', '발탁되기도', '오래', '보고', '들어온', '어른들께', '괜찮을거', '오늘',
    '소개해', '드릴', '정관장', '기다림', '침향환은', '전통', '과자', '강릉', '은정', '과자', '설날', '다가오면', '항상', '전통', '과자는', '어른들이', '특히', '좋아하시고',
    '강릉', '선물', '브랜드라', '신뢰도도', '높은', '깔끔해서', '이런', '좋은', '브랜드라', '실패', '확률이', '적은', '슈퍼', '바이탈', '라인은', '이미', '후기도', '워낙', '좋아서',
    '고민', '없이', '선택하기', '좋은', '그리고', '이것은', '한우', '육포', '맥주', '안주', '딱입니다', '추천템', '육포', '맥주', '안주', '딱입니다', '추천템', '홍삼선물세트',
    '등에', '찾다가', '고급', '있어', '관심이', '생겼는데요', '바로', '정관장', '기다림', '침향환', '여러분께', '라면', '익숙하실거라고', '성분이나', '호불호가', '갈릴', '수',
    '있음', '후기', '이중에', '세트', '추천하자면', '저는', '무조건', '해아린', '도라지정과', '일단', '흔하지', '않은', '과일', '한우처럼', '식상하지', '않아요'
]

# Prepare tokens for word cloud generation
all_tokens_for_wc = {}

for keyword, text in combined_descriptions.items():
    # Tokenize the text using Mecab (nouns are usually most informative for word clouds)
    nouns = mecab.nouns(text)
    # Filter out stopwords and single-character words
    filtered_nouns = [n for n in nouns if n not in korean_stopwords and len(n) > 1]
    all_tokens_for_wc[keyword] = " ".join(filtered_nouns)


# Generate and display word clouds for each keyword
for keyword, tokens in all_tokens_for_wc.items():
    wordcloud = WordCloud(font_path='/usr/share/fonts/nanum/NanumBarunGothic.ttf', # Specify Korean font
                          width=800, height=400,
                          background_color='white',
                          max_words=100,
                          colormap='viridis').generate(tokens)

    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title(f'워드 클라우드 - {keyword}')
    plt.show()